modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "quickbackupmulti_reforged"
version = "${version}"
displayName = "QuickBakcupMulti-Reforged"
authors = "SkyDynamic"
description = '''
A backup / restore mod, with multiple backup slots
'''
#logoFile = ""

[[dependencies.quickbackupmulti_reforged]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickbackupmulti_reforged]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5, )"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "quickbackupmulti.mixins.json"

[[mixins]]
config = "quickbackupmulti-neoforge.mixins.json"
