name: Dev Builds

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "*/src/**"
      - ".github/workflows/build.yml"
      - ".github/workflows/gradle.yml"
      - ".github/workflows/scripts/**"

  pull_request:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "*/src/**"
      - ".github/workflows/build.yml"
      - ".github/workflows/gradle.yml"
      - ".github/workflows/scripts/**"


jobs:
  build:
    uses: ./.github/workflows/build.yml