on:
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: The tag of the release you want to append the artifact to
        type: string
        required: true
      release:
        type: boolean
        required: true
        default: true
        description: is release workflow
  release:
    types:
      - published

jobs:
  show_action_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Show action parameters
        run: |
          cat <<EOF > $GITHUB_STEP_SUMMARY
          ## Action Parameters
          - target_release_tag: \`${{ github.event.inputs.target_release_tag }}\`
          EOF

  matrix_prep:
    uses: ./.github/workflows/matrix_prep.yml

  build_release:
    if: ${{ (github.event_name == 'release' && !github.event.release.prerelease) || (github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true') }}
    uses: ./.github/workflows/build.yml
    with:
      release: true

  build_alpha:
    if: ${{ !((github.event_name == 'release' && !github.event.release.prerelease) || (github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true')) }}
    uses: ./.github/workflows/build.yml

  release:
    needs:
      - matrix_prep
      - build_release
    uses: ./.github/workflows/publish.yml
    with:
      version-type: release
      matrix: ${{ needs.matrix_prep.outputs.matrix }}
    secrets:
      GT: ${{ secrets.GITHUB_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}

  release_alpha:
    needs:
      - matrix_prep
      - build_alpha
    uses: ./.github/workflows/publish.yml
    with:
      version-type: alpha
      matrix: ${{ needs.matrix_prep.outputs.matrix }}
    secrets:
      GT: ${{ secrets.GITHUB_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}